### ISSUE TITLE
手机端多次加入共享时，会接收到冗余信息

### ISSUE THREAD

**Issue by TobisLee** [nightmare-space/speed_share#1]
非常好用的软件，感谢开发者！

但是在使用时，手机端会出现一个如题的Bug。

【桌面环境】：Windows 10, 软件版本：v1.3.0
【手机环境】：小米6，软件版本：v1.3.1

【问题复现】：
1. 桌面版发起共享，手机端扫描二维码加入共享
2. 手机端退出共享，客户端保持不变
3. 手机端再次扫描二维码加入共享
4. 在手机端/桌面端发送消息，会看到一条冗余消息

【图片说明】：
【桌面端】：
![speed_share_win_pic](https://user-images.githubusercontent.com/17643538/161057498-97a34476-3921-484c-bc26-a6376eb8cf14.png)

【手机端】：
![xiaomi_pic_2](https://user-images.githubusercontent.com/17643538/161058204-167475e1-0205-4d8c-b9f3-ebb16f5bd397.jpg)

【其它说明】
1. 手机端无论通过“扫描二维码”还是“添加URL”加入桌面端共享时都会出现该问题。
2. 桌面端多次加入手机端共享不会出现该问题。

【Log】
![speed_share_log](https://user-images.githubusercontent.com/17643538/161060627-19509070-5629-4e91-bf60-4b9e69c29c75.jpg)

**Comment by mengyanshou** [comment]
反馈非常详细，感谢支持，最近速享正在大部分重构中，后续版本发布我会给你留言

**Comment by mengyanshou** [comment]
main分支的apk应该没有这个问题了，如果对这个问题还有疑问，你可以reopen这个issue
