### ISSUE TITLE
速享安卓APP使用mixplorer选择文件没有反应

### ISSUE THREAD

**Issue by Edfgdz** [nightmare-space/speed_share#10]
【手机环境】：红米Note8 Pro，软件版本：v 2.1.4，架构：arm64
【局域网环境】：家庭
【PC是否关闭防火墙】：没有PC
【问题复现】：打开速享APP，选择 系统管理器，然后选择 Mixplorer，在里面选取文件以后，文件无法传送到 速享 APP里面去

【视频说明】:  

https://user-images.githubusercontent.com/26460124/185267033-4d0692cb-d534-49c8-af23-18f5f9782b2e.mp4

【日志截图】:  
![Stitch182ae63dae6](https://user-images.githubusercontent.com/26460124/185267644-de8eaf10-7374-4f92-a968-ee322b1db4b6.png)

**Comment by mengyanshou** [comment]
收到，这其实是一个历史性的问题，我目前也还没有好的方法

**Comment by Edfgdz** [comment]
目前如果不使用mixplorer这一类的文件管理器来选择文件的话，有些文件路径比较长，上传文件会比较不方便，所以有可能的话看看能否有解决的可能

**Comment by mengyanshou** [comment]
用了不爱优雅的方式解决了，更新到了酷安

**Comment by Edfgdz** [comment]
下载了开发者个人服务器提供的版本以后

照着日志里面说的分享文件到mixplorer以后，安卓端能够显示分享的文件，但是网页端无法显示出来

![Screenshot_2022-08-21-17-51-40-155_com coolapk market](https://user-images.githubusercontent.com/26460124/185786042-c4ba4b9b-a63d-4ba4-a16a-02e9974bd7fc.jpg)


录屏

https://user-images.githubusercontent.com/26460124/185785999-0ae1c5f8-384d-40cb-af76-8be631364d15.mp4

日志

![Stitch182bfe2404f](https://user-images.githubusercontent.com/26460124/185786166-4d66cd36-8456-4716-827e-83745f25054c.png)

**Comment by Edfgdz** [comment]
这么做有另外一个问题

在使用SAF上传文件的时候。如果用户想要选择其他的选项来上传文件，而不是mixplorer的话，那么这次更新提供的通过从 mixplorer分享文件到 速享 的解决方法就没有很好的解决这个问题

![Screenshot_2022-08-21-19-42-09-377_com.android.documentsui.jpg](https://user-images.githubusercontent.com/26460124/185789352-fb271fa7-c00d-412c-96e5-26c8e0b466e1.jpg)

例如用户想要选择图库来上传文件的话，就会遇到问题

**Comment by mengyanshou** [comment]
是的，SAF这一直是个问题，有想到一个稍微好点的方法，但是需要较多工作量，暂时支持不上了

**Comment by mengyanshou** [comment]
网页端不能显示应该是另外的问题

**Comment by mengyanshou** [comment]
dev分支已经实现了支持所有SAF的文件分享，但是仍然有一些弊端，我先更新一个版本到酷安看看效果

**Comment by mengyanshou** [comment]
新版更新到酷安了，代码也推到了主分支，有问题可以再将这个issue打开
