### ISSUE TITLE
IOS web端文件上传问题

### ISSUE THREAD

**Issue by KJH-x** [nightmare-space/speed_share#13]
首先感谢作者，制作了如此方便的工具。

我在发现IOS使用web端的时候只能上传图片视频，其他文件没法上传（即使使用了“选取文件”按钮也被限制了文件格式，IOS里没法通过更改文件格式绕过），能多留一个文件选取吗，谢谢！

（我看到了QA里说暂时不会上架IOS才来问的）

**Comment by mengyanshou** [comment]
目前web上传文件在重构中，上传应该都是不生效的

**Comment by nbwzlyd** [comment]
什么时候重构好，现在web不能上传确实不方便，感谢大佬

**Comment by mengyanshou** [comment]
> 什么时候重构好，现在web不能上传确实不方便，感谢大佬

工作比较忙，着急用可以提pr

**Comment by mengyanshou** [comment]
酷安新版已经支持了，issue我先关闭了
