### ISSUE TITLE
官网的安卓版下载地址指向了adb tool而不是speedshare

### ISSUE THREAD

**Issue by shenmo7192** [nightmare-space/speed_share#19]
http://nightmare.fun/YanTool/resources/ADBTool/
应当是
http://nightmare.fun/YanTool/resources/SpeedShare/

同时建议使用蓝奏云，免费且高速

**Comment by mengyanshou** [comment]
去这儿下载 http://nightmare.fun/YanTool/resources/SpeedShare/ ，蓝奏云成本太高，5个项目，每次打包产物10多个
