### ISSUE TITLE
deepin 下无法正常打开

### ISSUE THREAD

**Issue by TheCoderChen** [nightmare-space/speed_share#2]
Deepin 系统下，下载Linux 版本，安装成功后，无法打开

**Comment by TheCoderChen** [comment]
在吗？这个项目还有人维护吗？

**Comment by mengyanshou** [comment]
如readme所说，目前正在大量的开发中，并且人力非常有限，这个issue有看到，我将标记为bug，等后面时间够了再来修复它

**Comment by DavidDengHui** [comment]
实测Deepin20可行没问题~
比系统自带的手机助手好用多啦！
![image](https://user-images.githubusercontent.com/15410727/170828345-1484f56a-6a4e-4089-bf7c-81cae5a94985.png)

**Comment by NitroRCr** [comment]
实测Ubuntu 20 也无法打开...

**Comment by mengyanshou** [comment]
下次构建我将使用ubuntu20的环境进行构建
