### ISSUE TITLE
已连接设备为0（偶现）

### ISSUE THREAD

**Issue by mengyanshou** [nightmare-space/speed_share#22]
- [x] 我已经阅读过 [FAQ](https://github.com/nightmare-space/speed_share/blob/main/QA.md).
 - [x] 我查找了现有的问题列表 [issues](https://github.com/nightmare-space/speed_share/issues).

**环境**
 - 系统: 所有
 - 速享版本: 2.1.6后

**描述这个问题**
经常会出现PC端与手机端只能单向通信的情况，并且偶尔能正常通信，但是已连接设备仍然未0，这个在我日常使用也经常遇到。

**Comment by Qunhang** [comment]
经常出现只能单向通信的情况。电脑打开热点，手机连上，浏览器上能查看手机文件，手机能向浏览器发送文件，但通过浏览器无法向手机传送文件，会提示“通知浏览器上传文件，这会比客户端慢一点”，实际上手机上能看到我想从浏览器传送的文件名，但是下载不了。此外，为什么不用电脑客户端，因为，电脑客户端既发不了，也收不了，设备数为0。但是这个软件的传输速度确实快，支持，希望这个问题能被解决。

**Comment by mengyanshou** [comment]
> 经常出现只能单向通信的情况。电脑打开热点，手机连上，浏览器上能查看手机文件，手机能向浏览器发送文件，但通过浏览器无法向手机传送文件，会提示“通知浏览器上传文件，这会比客户端慢一点”，实际上手机上能看到我想从浏览器传送的文件名，但是下载不了。此外，为什么不用电脑客户端，因为，电脑客户端既发不了，也收不了，设备数为0。但是这个软件的传输速度确实快，支持，希望这个问题能被解决。

看下PC的防火墙是否被关闭，然后更新速享所有版本到2.1.10再试试

**Comment by mengyanshou** [comment]
2.2.2版本已修复
