### ISSUE TITLE
有木有详细的部署教程啊

### ISSUE THREAD

**Issue by szsyzx** [nightmare-space/speed_share#30]
- [ ] 我已经阅读过 [FAQ](https://github.com/nightmare-space/speed_share/blob/main/QA.md).
 - [ ] 我查找了现有的问题列表 [issues](https://github.com/nightmare-space/speed_share/issues).

**环境**
 - 系统: [e.g. MIUI Android11]
 - 速享版本: [e.g. 2.1.6-1]

**描述这个问题**
有木有详细的部署教程啊
```
请粘贴日志到这儿
```

**截图**

**Comment by mengyanshou** [comment]
没听明白你想表达的意思

**Comment by szsyzx** [comment]
我是小白，请问怎么编译啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月18日(周二) 下午4:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nightmare-space/speed_share] 有木有详细的部署教程啊 (Issue #30)

**Comment by mengyanshou** [comment]
你到底想说啥，请表达清楚你的意思

**Comment by mengyanshou** [comment]
这只是一个客户端工程，我没有听过客户端工程为什么要部署，部署也只是后端接口才有的概念，需要编译请百度Flutter工程如何编译，如果纯小白，建议不要尝试自己编译该项目
