### ISSUE TITLE
Win10任务栏软件名称显示乱码

### ISSUE THREAD

**Issue by BahuangShanren** [nightmare-space/speed_share#32]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**

 - OS: Windows 10 专业版 21H2 19044.2075
 - SpeedShare: [v2.1.7](https://github.com/nightmare-space/speed_share/issues/31#issuecomment-1301595876)

**Describe the bug**

任务栏按钮不合并时，软件名称显示为乱码，如下图所示：

![image](https://user-images.githubusercontent.com/48022216/201513536-7f0fbd63-c48d-461d-8c89-c5468d349504.png)

**Comment by mengyanshou** [comment]
这个问题很奇怪，我本地构建的包没有这个问题，但是Github Actions打包出来的的确会有这个问题

**Comment by mengyanshou** [comment]
2.2.2版本已经修复
