### ISSUE TITLE
Android上发送消息如何换行？

### ISSUE THREAD

**Issue by BahuangShanren** [nightmare-space/speed_share#33]
- [x] 我已经阅读过 [FAQ](https://github.com/nightmare-space/speed_share/blob/main/QA.md).
 - [x] 我查找了现有的问题列表 [issues](https://github.com/nightmare-space/speed_share/issues).

**环境**
 - 系统: LineageOS Android11
 - 速享版本: 2.1.7

**描述这个问题**
消息窗口界面，虽然输入框提示`shift+enter`可以换行，但是Android键盘上没有`shift`，有什么替代方案吗？

**Comment by mengyanshou** [comment]
辛苦反馈，已经确定是bug，将在下个版本修复

**Comment by mengyanshou** [comment]
2.2.2版本已经修复
