### ISSUE TITLE
安卓自带的分享无法使用

### ISSUE THREAD

**Issue by wanzh5** [nightmare-space/speed_share#34]
- [ ] 我已经阅读过 [FAQ](https://github.com/nightmare-space/speed_share/blob/main/QA.md).
 - [ ] 我查找了现有的问题列表 [issues](https://github.com/nightmare-space/speed_share/issues).

**环境**
 - 系统: [harmonyos 2.0]
 - 速享版本: [2.1.9]

**描述这个问题**
直接将文件分享到速享的时候只能打开速享主页而无法直接传输文件，那分享形同虚设
```
请粘贴日志到这儿
```

**截图**

**Comment by mengyanshou** [comment]
为啥这个issue关闭了呀

**Comment by wanzh5** [comment]
忘记看FAQ了，发完发现FAQ里已经有这个问题了😂
