### ISSUE TITLE
flutter pub get的 时候报错

### ISSUE THREAD

**Issue by LikeNeko** [nightmare-space/speed_share#37]
- [x] 我已经阅读过 [FAQ](https://github.com/nightmare-space/speed_share/blob/main/QA.md).
 - [x] 我查找了现有的问题列表 [issues](https://github.com/nightmare-space/speed_share/issues).

**环境**
 - 系统: [e.g. MIUI Android11]
 - 速享版本: [e.g. 2.1.6-1]

**描述这个问题**
从master拉取代码，flutter pub get的 时候报错
```
Because speed_share depends on speed_share_extension from path which doesn't exist (could not find package speed_share_extension at "../speed_share_extension"), version solving failed.
```

```
请粘贴日志到这儿
```

**截图**

<img width="870" alt="image" src="https://user-images.githubusercontent.com/31497234/210986197-630064d6-f6a6-497d-8b38-f403753f9bf6.png">

**Comment by mengyanshou** [comment]
这个需要手动移除speed_share_exension库，再移除相关报错代码，这个库是非开源的，是会员才有的功能
