### ISSUE TITLE
剪贴板共享无法关闭

### ISSUE THREAD

**Issue by ZJH100** [nightmare-space/speed_share#38]
- [x] 我已经阅读过 [FAQ](https://github.com/nightmare-space/speed_share/blob/main/QA.md).
 - [x] 我查找了现有的问题列表 [issues](https://github.com/nightmare-space/speed_share/issues).

**环境**
 - 系统: [e.g. MIUI Android11]
 - 速享版本: [e.g. 2.1.6-1]

**描述这个问题**
剪贴板共享无法关闭？

**截图**
![image](https://user-images.githubusercontent.com/78086737/212478420-952535be-127f-472b-9563-3e957c4d53f7.png)
![image](https://user-images.githubusercontent.com/78086737/212478401-5ae4ef5a-0219-4f4b-b8d8-e7f673f088a9.png)

**Comment by mengyanshou** [comment]
2.2.2版本已修复
