### ISSUE TITLE
三星手机里隐私政策无法点击确定

### ISSUE THREAD

**Issue by wolfoooooo** [nightmare-space/speed_share#41]
- [x]  我已经阅读过 [FAQ](https://github.com/nightmare-space/speed_share/blob/main/QA.md).
 - [x]  我查找了现有的问题列表 [issues](https://github.com/nightmare-space/speed_share/issues).

**环境**
 - 系统: [Android. Galaxy S20. Android13]
 - 速享版本: [Android. 2.2.4-64]

**描述这个问题**
就是，隐私政策同意太低了，在返回按钮的下面无法点击。

```
请粘贴日志到这儿
```

**截图**
![](https://raw.githubusercontent.com/wolfoooooo/image/main/Screenshot_20230518_162139.jpg)

**Comment by mengyanshou** [comment]
更新到2.2.5试试
