### ISSUE TITLE
上架苹果商店

### ISSUE THREAD

**Issue by a83988029** [nightmare-space/speed_share#43]
- [x] 我已经阅读过 [需求清单](https://github.com/nightmare-space/speed_share/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%22) 没有存在这个需求.

**请描述这个需求关联的问题.**
上架苹果商店
**请描述建议的解决方案**
找个有苹果开发者账号的老哥就能上架苹果商店了

**请描述替代的解决方案**
找个有苹果开发者账号的老哥就能上架苹果商店了

**其他信息**
若无则留空

**Comment by mengyanshou** [comment]
首先“找个有苹果开发者账号的老哥就能上架苹果商店了”我并不认可，其次，几个月前我就自己购买开发者账号进行上架了，https://apps.apple.com/us/app/%E9%80%9F%E4%BA%AB/id6447294725
